spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo
      username: root
      password: rootpassword
      authentication-database: admin
  application:
    name: gradleproject

server:
  port: 8080