spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gradebookdb
    username: gradebook
    password: gradebook123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' or migrations in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: gradebook-app

server:
  port: 8080
